export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';

export const FETCH_COMPLIANT_START = 'FETCH_COMPLIANT_START';
export const FETCH_COMPLIANT_SUCCESS = 'FETCH_COMPLIANT_SUCCESS';
export const ADD_COMPLAINT_START = 'ADD_COMPLAINT_START';
export const ADD_COMPLAINT_SUCCESS = 'ADD_COMPLAINT_SUCCESS';

export const FETCH_BUZZ_START = 'FETCH_BUZZ_START';
export const FETCH_BUZZ_SUCCESS = 'FETCH_BUZZ_SUCCESS';
export const ADD_BUZZ_START = 'ADD_BUZZ_START';
export const ADD_BUZZ_SUCCESS = 'ADD_BUZZ_SUCCESS';
