/* User Actions */
export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';



/* Complaint Actions */
export const FETCH_COMPLAINT_START = 'FETCH_COMPLAINT_START';
export const FETCH_COMPLAINT_SUCCESS = 'FETCH_COMPLAINT_SUCCESS';
export const FETCH_COMPLAINT_FAILED = 'FETCH_COMPLAINT_FAILED';

export const ADD_COMPLAINT_START = 'ADD_COMPLAINT_START';
export const ADD_COMPLAINT_SUCCESS = 'ADD_COMPLAINT_SUCCESS';
export const ADD_COMPLAINT_FAILED = 'ADD_COMPLAINT_FAILED';
export const UPDATE_COMPLAINT = 'UPDATE_COMPLAINT';



/* Buzz Actions */
export const FETCH_BUZZ_START = 'FETCH_BUZZ_START';
export const FETCH_BUZZ_SUCCESS = 'FETCH_BUZZ_SUCCESS';
export const FETCH_BUZZ_FAILED = 'FETCH_BUZZ_FAILED';

export const LOAD_MORE_BUZZ_START = 'LOAD_MORE_BUZZ_START';
export const LOAD_MORE_BUZZ_SUCCESS = 'LOAD_MORE_BUZZ_SUCCESS';
export const LOAD_MORE_BUZZ_FAILED = 'LOAD_MORE_BUZZ_FAILED';

export const ADD_BUZZ_START = 'ADD_BUZZ_START';
export const ADD_BUZZ_SUCCESS = 'ADD_BUZZ_SUCCESS';
export const ADD_BUZZ_FAILED = 'ADD_BUZZ_FAILED';
export const LIKE_DISLIKE_BUZZ = 'LIKE_DISLIKE_BUZZ';

export const DELETE_BUZZ_START = 'DELETE_BUZZ_START';
export const DELETE_BUZZ_SUCCESSS = 'DELETE_BUZZ_SUCCESSS';
export const DELETE_BUZZ_FAILED = 'DELETE_BUZZ_FAILED';



/* Comment Actions */
export const FETCH_COMMENTS_START = 'FETCH_COMMENTS_START';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILED = 'FETCH_COMMENTS_FAILED';

export const LOAD_MORE_COMMENTS_START = 'LOAD_MORE_COMMENTS_START';
export const LOAD_MORE_COMMENTS_SUCCESS = 'LOAD_MORE_COMMENTS_SUCCESS';
export const LOAD_MORE_COMMENTS_FAILED = 'LOAD_MORE_COMMENTS_FAILED';

export const ADD_COMMENT_START = 'ADD_COMMENT_START';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILED = 'ADD_COMMENT_FAILED';

export const DELETE_COMMENT_START = 'DELETE_COMMENT_START';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILED = 'DELETE_COMMENT_FAILED';



/* Reply Actions */
export const FETCH_REPLIES_START = 'FETCH_REPLIES_START';
export const FETCH_REPLIES_SUCCESS = 'FETCH_REPLIES_SUCCESS';
export const FETCH_REPLIES_FAILED = 'FETCH_REPLIES_FAILED';

export const LOAD_MORE_REPLIES_START = 'LOAD_MORE_REPLIES_START';
export const LOAD_MORE_REPLIES_SUCCESS = 'LOAD_MORE_REPLIES_SUCCESS';
export const LOAD_MORE_REPLIES_FAILED = 'LOAD_MORE_REPLIES_FAILED';

export const ADD_REPLY_START = 'ADD_REPLY_START';
export const ADD_REPLY_SUCCESS = 'ADD_REPLY_SUCCESS';
export const ADD_REPLY_FAILED = 'ADD_REPLY_FAILED';

